name: Build Installer

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        name: Setup JDK 21
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Initialize caches
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/loom-cache
            ~/.gradle/wrapper
          key: ${{ runner.os }}-build-snapshot-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-build-snapshot-
      - name: Grant execute permission
        run: chmod +x gradlew
      - name: Build the mod
        run: ./gradlew --no-daemon build
      - uses: actions/upload-artifact@v4
        with:
          name: Iris-DH-Artifacts
          path: build/libs
